version: "3"

services:
  postgres:
    image: postgres:13
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: unichat
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5000:5432
    restart: always
  nodejs:
    build: .
    command: npm run start
    environment:
      - PORT=8000
      - NGINX_PORT=80
      - postgresHost=postgres
      - postgresPort=5432
      - postgresUser=postgres
      - postgresDB=postgres
      - postgresPass=root
      - issuer=localhost:8080
    restart: always
    depends_on:
      - postgres
    #  - redis
    ports:
      - 8080:80